export const CATEGORIES = [
  { id: 'fresh-flowers', name: 'Fresh Flowers', slug: 'fresh-flowers', image: '/assets/products/fresh-flowers.jpg', description: 'Fresh flowers commonly used and loved in Bengaluru' },
  { id: 'plants', name: 'Plants', slug: 'plants', image: '/assets/products/plants.jpg', description: 'Healthy indoor and outdoor potted plants' },
  { id: 'bouquets', name: 'Bouquets', slug: 'bouquets', image: '/assets/products/bouquets.jpg', description: 'Handcrafted luxury floral bouquets' },
  { id: 'seeds', name: 'Seeds', slug: 'seeds', image: '/assets/products/seeds.jpg', description: 'Premium packaged gardening seeds' },
  { id: 'decor', name: 'Decor', slug: 'decor', image: '/assets/products/decor.jpg', description: 'Artisan floral and botanical home decor' },
  { id: 'gift-combos', name: 'Gift Combos', slug: 'gift-combos', image: '/assets/products/gift-combos.jpg', description: 'Thoughtfully curated gift combinations' }
];

export const MOCK_PRODUCTS = [
  // ==========================================
  // 1. FRESH FLOWERS (EXACTLY 7 PRODUCTS)
  // ==========================================
  {
    id: 'fresh-flowers-1',
    name: 'Roses',
    slug: 'roses',
    shortDesc: 'Freshly cut, velvety crimson roses with long stems and intoxicating aroma.',
    longDesc: 'Our classic Bengaluru fresh roses are hand-picked at dawn from local climate-controlled farms. With crisp petals and deep crimson coloring, these fresh blooms bring timeless romance and natural beauty to any home.',
    category: 'fresh-flowers',
    price: 499,
    discount: 10,
    rating: 4.9,
    reviews: 142,
    stock: 25,
    sku: 'FRE-ROS-01',
    flowerMeaning: 'Deep love, passion, and admiration.',
    careInstructions: 'Trim stems diagonally and place in cold fresh water with flower food.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: true,
    image: '/assets/products/fresh-flowers-roses.jpg'
  },
  {
    id: 'fresh-flowers-2',
    name: 'Lilies',
    slug: 'lilies',
    shortDesc: 'Stately and pristine oriental white lilies with elegant starry blooms.',
    longDesc: 'Exquisite, aromatic white oriental lilies. Each stem features multiple fragrant buds that open gracefully over several days, perfuming your living space with majestic elegance.',
    category: 'fresh-flowers',
    price: 699,
    discount: 0,
    rating: 4.8,
    reviews: 98,
    stock: 18,
    sku: 'FRE-LIL-02',
    flowerMeaning: 'Purity, rebirth, and refined grace.',
    careInstructions: 'Remove stamens as the lilies open to avoid pollen staining and extend vase life.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: false,
    image: '/assets/products/fresh-flowers-lilies.jpg'
  },
  {
    id: 'fresh-flowers-3',
    name: 'Jasmine',
    slug: 'jasmine',
    shortDesc: 'Authentic fresh fragrant Jasmine (Mallige / Mogra) blossoms from Karnataka.',
    longDesc: 'Freshly harvested Arabian Jasmine (Jasminum sambac) blossoms, iconic to Bengaluru morning flower markets. Renowned for their celestial sweet fragrance, ideal for rituals, hair adornment, and serenity.',
    category: 'fresh-flowers',
    price: 349,
    discount: 5,
    rating: 5.0,
    reviews: 210,
    stock: 40,
    sku: 'FRE-JAS-03',
    flowerMeaning: 'Sensual sweetness, purity, and divine blessings.',
    careInstructions: 'Keep in a cool, ventilated container or mist lightly with fresh water.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: true,
    image: '/assets/products/fresh-flowers-jasmine.jpg'
  },
  {
    id: 'fresh-flowers-4',
    name: 'Marigold',
    slug: 'marigold',
    shortDesc: 'Vibrant golden orange and yellow Marigold (Genda) blooms for pooja and celebrations.',
    longDesc: 'Bright, auspicious golden marigold flowers hand-gathered from local Karnataka growers. With their intense golden-orange hue and grounding earthy scent, they are quintessential for traditional Indian festive celebrations.',
    category: 'fresh-flowers',
    price: 299,
    discount: 0,
    rating: 4.7,
    reviews: 135,
    stock: 50,
    sku: 'FRE-MAR-04',
    flowerMeaning: 'Auspiciousness, positive energy, and warmth of the sun.',
    careInstructions: 'Store in a cool shaded basket away from direct sunlight.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/fresh-flowers-marigold.jpg'
  },
  {
    id: 'fresh-flowers-5',
    name: 'Kanakambaram (Crossandra)',
    slug: 'kanakambaram-crossandra',
    shortDesc: 'Traditional radiant salmon-orange Kanakambaram flowers iconic in South India.',
    longDesc: 'Authentic fresh Kanakambaram (Crossandra infundibuliformis) flowers beloved throughout South Indian homes. Famous for their striking firecracker-orange hue and delicate ruffled petals, traditionally paired with jasmine.',
    category: 'fresh-flowers',
    price: 399,
    discount: 0,
    rating: 4.9,
    reviews: 88,
    stock: 30,
    sku: 'FRE-KAN-05',
    flowerMeaning: 'Grace, traditional heritage, and festive prosperity.',
    careInstructions: 'Keep wrapped loosely in banana leaf or cool moist cloth in refrigerator until use.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: false,
    image: '/assets/products/fresh-flowers-kanakambaram.jpg'
  },
  {
    id: 'fresh-flowers-6',
    name: 'Chrysanthemum',
    slug: 'chrysanthemum',
    shortDesc: 'Lush and cheerful fresh yellow Chrysanthemum (Shevanti) flowers.',
    longDesc: 'Freshly harvested yellow Chrysanthemum (Shevanti) flowers with dense, symmetrical ray florets. A staple across Bengaluru floral bazaars for home decor, ceremonies, and festive rangolis.',
    category: 'fresh-flowers',
    price: 379,
    discount: 8,
    rating: 4.8,
    reviews: 74,
    stock: 35,
    sku: 'FRE-CHRY-06',
    flowerMeaning: 'Optimism, joy, and long life.',
    careInstructions: 'Keep stems moist and avoid keeping blooms in direct hot wind.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: false,
    image: '/assets/products/fresh-flowers-chrysanthemum.jpg'
  },
  {
    id: 'fresh-flowers-7',
    name: 'Gerbera',
    slug: 'gerbera',
    shortDesc: 'Bright, colorful modern Gerbera daisies with sturdy stems and long vase life.',
    longDesc: 'Freshly picked, vibrant Gerbera daisies cultivated in high-tech polyhouses. Featuring bold, saturated petals that brighten any tabletop or modern vase arrangement for up to two weeks.',
    category: 'fresh-flowers',
    price: 449,
    discount: 0,
    rating: 4.7,
    reviews: 62,
    stock: 22,
    sku: 'FRE-GER-07',
    flowerMeaning: 'Cheerfulness, loyal love, and innocent joy.',
    careInstructions: 'Use minimal water in the vase (about 2 inches) and change daily to prevent stem rot.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: false,
    image: '/assets/products/fresh-flowers-gerbera.jpg'
  },

  // ==========================================
  // 2. PLANTS (EXACTLY 7 PRODUCTS)
  // ==========================================
  {
    id: 'plants-1',
    name: 'Money Plant',
    slug: 'money-plant',
    shortDesc: 'Potted trailing variegated Golden Pothos known for air purification and good fortune.',
    longDesc: 'A lush, thriving Golden Pothos Money Plant in an artisanal pot. Easy to care for and adaptable to both bright and low indoor lighting, it naturally cleans indoor toxins and symbolizes abundance.',
    category: 'plants',
    price: 499,
    discount: 10,
    rating: 4.9,
    reviews: 180,
    stock: 28,
    sku: 'PLN-MON-01',
    flowerMeaning: 'Prosperity, wealth, and continuous growth.',
    careInstructions: 'Water once a week when top soil feels dry; thrives in indirect ambient light.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: true,
    image: '/assets/products/plants-money-plant.jpg'
  },
  {
    id: 'plants-2',
    name: 'Snake Plant',
    slug: 'snake-plant',
    shortDesc: 'Architectural Sansevieria plant that releases oxygen even at night.',
    longDesc: 'Hardy and sculptural Sansevieria trifasciata Laurentii with striking yellow-bordered upright foliage. Highly recommended by NASA for superior bedroom air filtration and virtually indestructible.',
    category: 'plants',
    price: 599,
    discount: 0,
    rating: 4.9,
    reviews: 156,
    stock: 20,
    sku: 'PLN-SNK-02',
    flowerMeaning: 'Tenacity, endurance, and protective positive energy.',
    careInstructions: 'Water sparsely every 2-3 weeks; thrives in low to medium indirect light.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: false,
    image: '/assets/products/plants-snake-plant.jpg'
  },
  {
    id: 'plants-3',
    name: 'Hibiscus Plant',
    slug: 'hibiscus-plant',
    shortDesc: 'Blooming tropical red Hibiscus plant in sturdy gardening pot.',
    longDesc: 'Healthy, bushy tropical Hibiscus plant with glossy deep-green foliage and abundant flowering buds that open into showstopping red blossoms. Perfect for balconies, terraces, and sunny windows.',
    category: 'plants',
    price: 449,
    discount: 0,
    rating: 4.7,
    reviews: 94,
    stock: 19,
    sku: 'PLN-HIB-03',
    flowerMeaning: 'Delicate beauty, fame, and auspicious devotion.',
    careInstructions: 'Requires at least 4-5 hours of direct sunlight daily and regular soil moisture.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/plants-hibiscus-plant.jpg'
  },
  {
    id: 'plants-4',
    name: 'Aloe Vera Plant',
    slug: 'aloe-vera-plant',
    shortDesc: 'Medicinal and soothing succulent Aloe Vera in a stylish container.',
    longDesc: 'Plump and healthy Aloe Vera plant filled with natural soothing gel. An indispensable healing succulent that requires almost zero maintenance while purifying the surrounding air.',
    category: 'plants',
    price: 349,
    discount: 0,
    rating: 4.8,
    reviews: 112,
    stock: 35,
    sku: 'PLN-ALO-04',
    flowerMeaning: 'Healing, regeneration, and resilience.',
    careInstructions: 'Allow soil to dry out completely between waterings; place in bright sunny spot.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: false,
    image: '/assets/products/plants-aloe-vera-plant.jpg'
  },
  {
    id: 'plants-5',
    name: 'Peace Lily',
    slug: 'peace-lily',
    shortDesc: 'Graceful Spathiphyllum with deep glossy leaves and pure white spathes.',
    longDesc: 'An elegant Peace Lily indoor plant potted in a designer ceramic pot. Renowned for its calming white blooms and exceptional capability to absorb airborne VOCs and restore indoor humidity.',
    category: 'plants',
    price: 649,
    discount: 12,
    rating: 4.9,
    reviews: 140,
    stock: 22,
    sku: 'PLN-PCE-05',
    flowerMeaning: 'Peace, tranquility, and harmony.',
    careInstructions: 'Keep in medium indirect light; water when leaves begin to show slight drooping.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: false,
    image: '/assets/products/plants-peace-lily.jpg'
  },
  {
    id: 'plants-6',
    name: 'Areca Palm',
    slug: 'areca-palm',
    shortDesc: 'Feathery tropical indoor palm that creates an instant urban oasis.',
    longDesc: 'Lush and graceful Dypsis lutescens Areca Palm featuring soft, arching feathery fronds. Adds natural tropical grandeur to living rooms, offices, and entry foyers while acting as a natural humidifier.',
    category: 'plants',
    price: 799,
    discount: 0,
    rating: 4.8,
    reviews: 83,
    stock: 15,
    sku: 'PLN-ARC-06',
    flowerMeaning: 'Victory, peace, and welcoming hospitality.',
    careInstructions: 'Place in bright filtered sunlight; water when the top inch of soil is dry.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: false,
    image: '/assets/products/plants-areca-palm.jpg'
  },
  {
    id: 'plants-7',
    name: 'Jade Plant',
    slug: 'jade-plant',
    shortDesc: 'Fleshy-leaved Crassula ovata succulent symbolizing good luck and prosperity.',
    longDesc: 'Compact and charming Jade Plant succulent with coin-shaped jade green leaves and thick woody stems. A beloved Feng Shui and Vastu favorite believed to attract financial abundance.',
    category: 'plants',
    price: 499,
    discount: 0,
    rating: 4.7,
    reviews: 79,
    stock: 24,
    sku: 'PLN-JAD-07',
    flowerMeaning: 'Good luck, fortune, and friendship.',
    careInstructions: 'Keep in bright sunlight or sunny windowsill; water only when completely dry.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: false,
    image: '/assets/products/plants-jade-plant.jpg'
  },

  // ==========================================
  // 3. BOUQUETS (EXACTLY 7 PRODUCTS)
  // ==========================================
  {
    id: 'bouquets-1',
    name: 'Classic Red Rose Bouquet',
    slug: 'classic-red-rose-bouquet',
    shortDesc: 'Grand luxury hand-tied bouquet of freshly cut deep crimson roses.',
    longDesc: 'A magnificent signature bouquet crafted with premium long-stemmed red roses, baby\'s breath accents, and silver dollar eucalyptus, hand-wrapped in imported luxury matte paper and finished with satin ribbon.',
    category: 'bouquets',
    price: 1299,
    discount: 15,
    rating: 5.0,
    reviews: 245,
    stock: 20,
    sku: 'BOU-RED-01',
    flowerMeaning: 'Passionate devotion, romance, and unending love.',
    careInstructions: 'Recut stems under running water and place in fresh water away from draft.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: true,
    image: '/assets/products/bouquets-classic-red-rose.jpg'
  },
  {
    id: 'bouquets-2',
    name: 'Pink Rose Bouquet',
    slug: 'pink-rose-bouquet',
    shortDesc: 'Romantic and delicate arrangement of sweet pink roses wrapped in blush kraft paper.',
    longDesc: 'An enchanting bouquet of blush and cherry pink roses paired with delicate white filler flowers. Styled with timeless elegance to celebrate birthdays, thank-yous, and special moments.',
    category: 'bouquets',
    price: 1199,
    discount: 0,
    rating: 4.8,
    reviews: 130,
    stock: 18,
    sku: 'BOU-PNK-02',
    flowerMeaning: 'Gratitude, sweetness, and admiration.',
    careInstructions: 'Keep in a cool room away from fruit bowls and direct heat.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: false,
    image: '/assets/products/bouquets-pink-rose.jpg'
  },
  {
    id: 'bouquets-3',
    name: 'Lily Elegance Bouquet',
    slug: 'lily-elegance-bouquet',
    shortDesc: 'Sophisticated luxury bouquet featuring white lilies, cream roses, and seasonal foliage.',
    longDesc: 'An opulent arrangement showcasing pristine white Asiatic lilies in full bloom alongside ivory spray roses and verdant eucalyptus leaves. The epitome of modern grace and luxury.',
    category: 'bouquets',
    price: 1499,
    discount: 10,
    rating: 4.9,
    reviews: 110,
    stock: 15,
    sku: 'BOU-LIL-03',
    flowerMeaning: 'Majesty, pure devotion, and celebration of new beginnings.',
    careInstructions: 'Gently snip stamens as petals open; replenish water every 48 hours.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: false,
    image: '/assets/products/bouquets-lily-elegance.jpg'
  },
  {
    id: 'bouquets-4',
    name: 'Mixed Flower Bouquet',
    slug: 'mixed-flower-bouquet',
    shortDesc: 'Vibrant celebratory bouquet blending colorful roses, carnations, and daisies.',
    longDesc: 'A joyful and lively arrangement bursting with an eclectic mix of seasonal fresh blooms in harmonious jewel tones. Designed to bring instant sunshine and heartfelt cheer to any recipient.',
    category: 'bouquets',
    price: 999,
    discount: 0,
    rating: 4.7,
    reviews: 165,
    stock: 25,
    sku: 'BOU-MIX-04',
    flowerMeaning: 'Joy, friendship, and happy celebration.',
    careInstructions: 'Change vase water every two days for maximum flower longevity.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/bouquets-mixed-flower.jpg'
  },
  {
    id: 'bouquets-5',
    name: 'White & Green Bouquet',
    slug: 'white-and-green-bouquet',
    shortDesc: 'Clean and modern botanical bouquet of white blossoms and lush greenery.',
    longDesc: 'An understated, high-fashion botanical bouquet combining pure white blooms with variegated foliage, baby eucalyptus, and crisp botanicals for a refreshing architectural aesthetic.',
    category: 'bouquets',
    price: 1399,
    discount: 0,
    rating: 4.8,
    reviews: 82,
    stock: 14,
    sku: 'BOU-WHT-05',
    flowerMeaning: 'Peace, refined clarity, and timeless sophistication.',
    careInstructions: 'Mist foliage lightly and keep water level high.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: false,
    image: '/assets/products/bouquets-white-green.jpg'
  },
  {
    id: 'bouquets-6',
    name: 'Pastel Flower Bouquet',
    slug: 'pastel-flower-bouquet',
    shortDesc: 'Dreamy arrangement of soft blush, lavender, and peach pastel blooms.',
    longDesc: 'A poetic hand-tied bouquet featuring delicate pastel roses, lisianthus, and airy baby\'s breath wrapped in fine translucent vellum paper. Soft, dreamy, and utterly romantic.',
    category: 'bouquets',
    price: 1249,
    discount: 0,
    rating: 4.9,
    reviews: 97,
    stock: 16,
    sku: 'BOU-PAS-06',
    flowerMeaning: 'Tender love, gentle beauty, and grace.',
    careInstructions: 'Keep in cool environment and change vase water regularly.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: false,
    image: '/assets/products/bouquets-pastel-flower.jpg'
  },
  {
    id: 'bouquets-7',
    name: 'Sunshine Yellow Bouquet',
    slug: 'sunshine-yellow-bouquet',
    shortDesc: 'Radiant bouquet of sunny yellow roses and golden blossoms tied with gold ribbon.',
    longDesc: 'A radiant floral burst featuring cheerful yellow roses, golden spray blooms, and fresh greenery. Designed to convey warmth, encouragement, and sincere congratulations.',
    category: 'bouquets',
    price: 1099,
    discount: 5,
    rating: 4.7,
    reviews: 75,
    stock: 22,
    sku: 'BOU-YEL-07',
    flowerMeaning: 'Happiness, warm friendship, and success.',
    careInstructions: 'Ensure stems are cleanly cut and placed in fresh lukewarm water.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: false,
    image: '/assets/products/bouquets-sunshine-yellow.jpg'
  },

  // ==========================================
  // 4. SEEDS (EXACTLY 7 PRODUCTS)
  // ==========================================
  {
    id: 'seeds-1',
    name: 'Rose Seeds',
    slug: 'rose-seeds',
    shortDesc: 'Heirloom packaged fragrant flowering Rose bush seeds with 90% germination.',
    longDesc: 'Carefully packaged, non-GMO heirloom Rose seeds packed in an airtight kraft packet with detailed step-by-step planting guidelines. Grow your own fragrant garden roses from scratch.',
    category: 'seeds',
    price: 199,
    discount: 0,
    rating: 4.6,
    reviews: 89,
    stock: 45,
    sku: 'SED-ROS-01',
    flowerMeaning: 'Cultivation of enduring love and floral craft.',
    careInstructions: 'Sow in well-draining seed starter mix; germinate under warm indirect light.',
    deliveryTime: '2-3 Days',
    featured: true,
    bestSeller: true,
    image: '/assets/products/seeds-rose-seeds.jpg'
  },
  {
    id: 'seeds-2',
    name: 'Marigold Seeds',
    slug: 'marigold-seeds',
    shortDesc: 'High-germination French & African Marigold seeds packet for vibrant blooms.',
    longDesc: 'Specially treated, disease-resistant Marigold seeds in vintage-style botanical packaging. Fast-growing and hardy, perfect for home balconies, terrace gardens, and natural pest deterrence.',
    category: 'seeds',
    price: 149,
    discount: 0,
    rating: 4.8,
    reviews: 145,
    stock: 60,
    sku: 'SED-MAR-02',
    flowerMeaning: 'Festive prosperity and cheerful garden vibrancy.',
    careInstructions: 'Scatter seeds on loose soil, lightly cover, and water with gentle spray.',
    deliveryTime: '2-3 Days',
    featured: true,
    bestSeller: true,
    image: '/assets/products/seeds-marigold-seeds.jpg'
  },
  {
    id: 'seeds-3',
    name: 'Sunflower Seeds',
    slug: 'sunflower-seeds',
    shortDesc: 'Mammoth golden Sunflower seeds in attractive moisture-proof gardening packaging.',
    longDesc: 'Giant Russian and Mammoth Sunflower seeds selected for towering height and enormous golden flower heads. Highly popular for beginner gardeners and pollinator friendly landscapes.',
    category: 'seeds',
    price: 179,
    discount: 0,
    rating: 4.9,
    reviews: 120,
    stock: 50,
    sku: 'SED-SUN-03',
    flowerMeaning: 'Radiance, warmth, and sunny positivity.',
    careInstructions: 'Plant 1 inch deep in direct full sunlight; water regularly until established.',
    deliveryTime: '2-3 Days',
    featured: true,
    bestSeller: false,
    image: '/assets/products/seeds-sunflower-seeds.jpg'
  },
  {
    id: 'seeds-4',
    name: 'Jasmine Seeds',
    slug: 'jasmine-seeds',
    shortDesc: 'Aromatic Arabian Jasmine climber seeds in protective botanical seed packet.',
    longDesc: 'Genuine Jasmine flower seeds packet for growing fragrant flowering climbers and hedges. Ideal for trellis training and filling warm evenings with natural intoxicating fragrance.',
    category: 'seeds',
    price: 229,
    discount: 10,
    rating: 4.7,
    reviews: 67,
    stock: 35,
    sku: 'SED-JAS-04',
    flowerMeaning: 'Spiritual bliss and timeless sweetness.',
    careInstructions: 'Soak seeds in lukewarm water for 24 hours prior to sowing in fertile soil.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/seeds-jasmine-seeds.jpg'
  },
  {
    id: 'seeds-5',
    name: 'Hibiscus Seeds',
    slug: 'hibiscus-seeds',
    shortDesc: 'Tropical giant-bloom Hibiscus seeds packaged in resealable gardening envelope.',
    longDesc: 'Premium mixed hybrid Hibiscus seeds capable of producing spectacular multi-colored blooms. Each seed packet contains 25+ seeds tested for vigor and high germination rates.',
    category: 'seeds',
    price: 219,
    discount: 0,
    rating: 4.6,
    reviews: 58,
    stock: 40,
    sku: 'SED-HIB-05',
    flowerMeaning: 'Bold beauty and tropical splendor.',
    careInstructions: 'Sow in rich organic loam; keep soil consistently warm and damp.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/seeds-hibiscus-seeds.jpg'
  },
  {
    id: 'seeds-6',
    name: 'Tomato Seeds',
    slug: 'tomato-seeds',
    shortDesc: 'Heirloom juicy sweet garden Tomato seeds in certified seed packaging.',
    longDesc: 'All-natural heirloom cherry and vine Tomato seeds for homegrown kitchen gardens. Packed with sweet flavor, disease tolerance, and exceptional yields in containers or garden beds.',
    category: 'seeds',
    price: 149,
    discount: 0,
    rating: 4.8,
    reviews: 190,
    stock: 75,
    sku: 'SED-TOM-06',
    flowerMeaning: 'Abundance, culinary joy, and homegrown wellness.',
    careInstructions: 'Start indoors or in trays; transplant into full sun with garden stake support.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: true,
    image: '/assets/products/seeds-tomato-seeds.jpg'
  },
  {
    id: 'seeds-7',
    name: 'Basil Seeds',
    slug: 'basil-seeds',
    shortDesc: 'Organic Italian Sweet Basil seeds packaged in airtight foil-lined seed pouch.',
    longDesc: 'Aromatic Sweet Genovese Basil seeds for fresh culinary herb harvesting. Grows vigorously on sunny windowsills, providing fresh, zesty leaves for homemade pestos, pastas, and teas.',
    category: 'seeds',
    price: 169,
    discount: 0,
    rating: 4.9,
    reviews: 134,
    stock: 55,
    sku: 'SED-BAS-07',
    flowerMeaning: 'Good wishes, love, and culinary harmony.',
    careInstructions: 'Sow shallowly on surface; pinch back growing tips to encourage bushy growth.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/seeds-basil-seeds.jpg'
  },

  // ==========================================
  // 5. DECOR (EXACTLY 4 PRODUCTS)
  // ==========================================
  {
    id: 'decor-1',
    name: 'Table Decor',
    slug: 'table-decor',
    shortDesc: 'Bespoke dining table floral runner with cascading roses, greenery, and candles.',
    longDesc: 'A breathtaking banquet table centerpiece crafted with luxury silk roses, eucalyptus runners, and glass hurricane votives. Designed to elevate romantic dinners, festive parties, and elegant gatherings.',
    category: 'decor',
    price: 2499,
    discount: 10,
    rating: 4.9,
    reviews: 64,
    stock: 12,
    sku: 'DEC-TAB-01',
    flowerMeaning: 'Elegance, celebration, and exquisite hospitality.',
    careInstructions: 'Dust gently with feather duster; store in protective box when not displayed.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: true,
    image: '/assets/products/decor-table-decor.jpg'
  },
  {
    id: 'decor-2',
    name: 'Festive Decor',
    slug: 'festive-decor',
    shortDesc: 'Traditional entrance decor with dense marigold garlands, brass urli, and glowing diyas.',
    longDesc: 'Traditional Indian festive floral styling ensemble featuring hand-strung golden marigold garlands, fragrant rose petals, and handcrafted brass accents. Perfect for Diwali, housewarmings, and weddings.',
    category: 'decor',
    price: 1999,
    discount: 0,
    rating: 5.0,
    reviews: 82,
    stock: 15,
    sku: 'DEC-FES-02',
    flowerMeaning: 'Divine blessings, auspicious prosperity, and celebratory warmth.',
    careInstructions: 'Mist marigold garlands lightly with cold water before hanging to maintain freshness.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: true,
    image: '/assets/products/decor-festive-decor.jpg'
  },
  {
    id: 'decor-3',
    name: 'Hanging Decor',
    slug: 'hanging-decor',
    shortDesc: 'Artisanal hanging floral basket with cascading blooms and trailing greenery.',
    longDesc: 'A delightful hanging botanical basket featuring suspended trailing ivy, vibrant seasonal petunias, and cascading blooms. Perfect for balconies, verandas, pergolas, and garden porticos.',
    category: 'decor',
    price: 1499,
    discount: 0,
    rating: 4.8,
    reviews: 48,
    stock: 18,
    sku: 'DEC-HNG-03',
    flowerMeaning: 'Graceful abundance and elevating natural beauty.',
    careInstructions: 'Hang securely on strong ceiling hook; water gently allowing excess to drain.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: false,
    image: '/assets/products/decor-hanging-decor.jpg'
  },
  {
    id: 'decor-4',
    name: 'Living Wall Decor',
    slug: 'living-wall-decor',
    shortDesc: 'Round wooden framed preserved moss and living botanical floral wall art.',
    longDesc: 'A high-end architectural living art piece featuring 100% naturally preserved green mosses, ferns, and botanical elements nestled inside a handcrafted hardwood frame. Zero watering required.',
    category: 'decor',
    price: 3299,
    discount: 15,
    rating: 5.0,
    reviews: 53,
    stock: 10,
    sku: 'DEC-WAL-04',
    flowerMeaning: 'Enduring nature, stillness, and organic serenity.',
    careInstructions: 'No watering or sunlight required; maintain in standard indoor room conditions.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: false,
    image: '/assets/products/decor-living-wall-decor.jpg'
  },

  // ==========================================
  // 6. GIFT COMBOS (EXACTLY 7 PRODUCTS)
  // ==========================================
  {
    id: 'gift-combos-1',
    name: 'Flowers + Cake',
    slug: 'flowers-plus-cake',
    shortDesc: 'Freshly bloomed red rose bouquet paired with a gourmet chocolate celebration cake.',
    longDesc: 'The ultimate birthday and anniversary delight! A hand-tied bouquet of fresh crimson roses accompanied by a freshly baked 500g rich chocolate truffle cake crafted by artisanal Bengaluru bakers.',
    category: 'gift-combos',
    price: 1799,
    discount: 10,
    rating: 5.0,
    reviews: 189,
    stock: 20,
    sku: 'GFT-CAK-01',
    flowerMeaning: 'Celebration, sweetness, and joyous occasions.',
    careInstructions: 'Keep cake refrigerated until cutting; place flower stems in fresh water.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: true,
    image: '/assets/products/gift-combos-flowers-cake.jpg'
  },
  {
    id: 'gift-combos-2',
    name: 'Flowers + Teddy Bear',
    slug: 'flowers-plus-teddy-bear',
    shortDesc: 'Romantic pink floral bouquet with an adorable, cuddly plush teddy bear.',
    longDesc: 'A heart-melting gift pairing fresh premium pink and red blooms with a super-soft, premium plush teddy bear (30 cm). The sweetest way to send warm hugs and romantic affection across town.',
    category: 'gift-combos',
    price: 1499,
    discount: 0,
    rating: 4.9,
    reviews: 115,
    stock: 25,
    sku: 'GFT-TED-02',
    flowerMeaning: 'Affection, gentle comfort, and caring hugs.',
    careInstructions: 'Teddy bear is surface washable; keep blooms hydrated in a clean vase.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: false,
    image: '/assets/products/gift-combos-flowers-teddy-bear.jpg'
  },
  {
    id: 'gift-combos-3',
    name: 'Flowers + Chocolates',
    slug: 'flowers-plus-chocolates',
    shortDesc: 'Handcrafted floral arrangement paired with a luxury box of premium chocolates.',
    longDesc: 'A luxurious pairing of hand-picked seasonal flowers and a 16-piece golden box of imported Ferrero Rocher hazelnut chocolates. Classic, indulgent, and universally adored.',
    category: 'gift-combos',
    price: 1399,
    discount: 5,
    rating: 4.8,
    reviews: 148,
    stock: 30,
    sku: 'GFT-CHO-03',
    flowerMeaning: 'Pure indulgence and sweet celebration.',
    careInstructions: 'Store chocolates in a cool dry place below 20°C; trim flower stems.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: true,
    image: '/assets/products/gift-combos-flowers-chocolates.jpg'
  },
  {
    id: 'gift-combos-4',
    name: 'Flowers + Cake + Chocolates',
    slug: 'flowers-plus-cake-plus-chocolates',
    shortDesc: 'Grand celebratory combo of fresh roses, artisan chocolate cake, and chocolate box.',
    longDesc: 'The complete party in a box! Features a lush 12-stem rose bouquet, a decadent 500g chocolate cake, and a box of premium assorted chocolate truffles. Perfect for milestone birthdays and anniversaries.',
    category: 'gift-combos',
    price: 2299,
    discount: 15,
    rating: 5.0,
    reviews: 92,
    stock: 15,
    sku: 'GFT-ALL-04',
    flowerMeaning: 'Grand celebration, unbounded joy, and luxury.',
    careInstructions: 'Refrigerate cake immediately upon doorstep delivery.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/gift-combos-flowers-cake-chocolates.jpg'
  },
  {
    id: 'gift-combos-5',
    name: 'Flowers + Teddy + Chocolates',
    slug: 'flowers-plus-teddy-plus-chocolates',
    shortDesc: 'Delightful trio of romantic blossoms, cuddly plush bear, and gourmet chocolates.',
    longDesc: 'A complete romantic gift set consisting of a fresh red rose hand-tied bouquet, an adorable plush teddy bear, and a premium box of creamy chocolates. Guaranteed to bring unforgettable smiles.',
    category: 'gift-combos',
    price: 1999,
    discount: 10,
    rating: 4.9,
    reviews: 84,
    stock: 18,
    sku: 'GFT-TCH-05',
    flowerMeaning: 'Romantic tenderness and warm sweet affection.',
    careInstructions: 'Place bouquet in water immediately; keep chocolates cool.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: false,
    image: '/assets/products/gift-combos-flowers-teddy-chocolates.jpg'
  },
  {
    id: 'gift-combos-6',
    name: 'Flowers + Candle',
    slug: 'flowers-plus-candle',
    shortDesc: 'Fresh floral bouquet accompanied by an aromatherapy scented soy jar candle.',
    longDesc: 'A soothing relaxation and self-care gift combo. Includes a lovely bouquet of fresh flowers paired with a luxury hand-poured lavender-vanilla soy candle that burns cleanly for 40+ hours.',
    category: 'gift-combos',
    price: 1599,
    discount: 0,
    rating: 4.8,
    reviews: 71,
    stock: 22,
    sku: 'GFT-CND-06',
    flowerMeaning: 'Serenity, mindfulness, and warm gentle light.',
    careInstructions: 'Trim candle wick to 1/4 inch before lighting; never leave burning candle unattended.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: false,
    image: '/assets/products/gift-combos-flowers-candle.jpg'
  },
  {
    id: 'gift-combos-7',
    name: 'Flowers + Greeting Card',
    slug: 'flowers-plus-greeting-card',
    shortDesc: 'Fresh bouquet paired with an elegant personalized handwritten greeting card.',
    longDesc: 'Express your feelings with heart and elegance. A fresh hand-tied floral bouquet delivered alongside a premium gold-embossed greeting card inscribed with your custom heartfelt personal message.',
    category: 'gift-combos',
    price: 999,
    discount: 0,
    rating: 4.9,
    reviews: 130,
    stock: 40,
    sku: 'GFT-CRD-07',
    flowerMeaning: 'Heartfelt words, sincere connection, and fond memories.',
    careInstructions: 'Keep card dry as a keepsake; recut flower stems every 2 days.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: false,
    image: '/assets/products/gift-combos-flowers-greeting-card.jpg'
  }
];
